### ISSUE TITLE
Integration doesn't work with Learning Locker V2 

### ISSUE THREAD

**Issue by amirshurrab** [davidpesce/moodle-mod_tincanlaunch#145] opened 2017-12-19 12:00 UTC
I have this plugin installed on moodle and the integration with learning locker V2 is done correctly but in the LRS it only shows that i've launched the XAPI packages not the other statements , however i tried to connect it to learning locker V1 and it worked okay , so i was asking if this plugin is outdated , does it only support version 1 of learning locker LRS?

**Comment by garemoko** [comment] 2017-12-19 13:06
Duplicate of https://github.com/garemoko/moodle-mod_tincanlaunch/issues/144

**Closed as completed by garemoko** 2017-12-19 13:06 UTC
